extraction:
  cpp:
    after_prepare:
      - mkdir $HOME/cmake-3.18 \
          \ && wget -qO- "https://cmake.org/files/v3.18/cmake-3.18.3-Linux-x86_64.tar.gz" \
            \ | tar -xzf - --strip-components=1 -C $HOME/cmake-3.18
      - export PATH=$HOME/cmake-3.18/bin:$PATH
path_classifiers:
  test:
    - "/libvast/test/**/*.cpp"
  scripts:
    - exclude: "/scripts/"
  library:
    - exclude: "/libvast/aux/"
  docs:
    - generate_javadoc.py
queries:
  - exclude: cpp/use-of-goto  
