version: "3"
services:
  vast:
    container_name: tenzir-vast
    image: tenzir/vast:${VAST_VERSION:-latest}
    environment:
      - VAST_ENDPOINT=vast:42000
    ports:
      - ${VAST_PORT:-42000}:42000
    command:
      - start
    volumes:
      - vast-data:/var/lib/vast/
      - vast-log:/var/log/vast/
    networks:
      - vast-network

volumes:
  vast-data:
    driver: local
  vast-log:
    driver: local

networks:
  vast-network:
    driver: bridge

