version: "3"
services:
  thehive:
    image: strangebee/thehive:latest
    container_name: thehive
    mem_limit: 1000m
    depends_on:
      - cassandra
      - elasticsearch
      - minio
    ports:
      - "9000:9000"
    environment:
      - JVM_OPTS="-Xms1024M -Xmx1024M"
    command:
      - --secret
      - "mySecretForTheHive"
      - "--cql-hostnames"
      - "cassandra"
      - "--cql-username"
      - "cassandra"
      - "--cql-password"
      - "cassandra"
      - "--index-backend"
      - "elasticsearch"
      - "--es-hostnames"
      - "elasticsearch"
      - "--s3-endpoint"
      - "http://minio:9000"
      - "--s3-access-key"
      - "minioadmin"
      - "--s3-secret-key"
      - "minioadmin"
      - "--s3-use-path-access-style"
      - "--no-config-cortex"
    volumes:
      - ./vol/thehive/application.conf:/etc/thehive/application.conf
      - thehive-data:/opt/thp/thehive/data
 #    - thehive-index:/opt/thp/thehive/index

  cassandra:
    container_name: cassandra
    image: bitnami/cassandra
    mem_limit: 1000m
    ports:
      - "9042:9042"
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=512M
      - CASSANDRA_CLUSTER_NAME=TheHive
    volumes:
      - cassandra-data:/var/lib/cassandra/data

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    mem_limit: 1000m
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-logs:/usr/share/elasticsearch/logs

  minio:
    container_name: minio
    image: quay.io/minio/minio
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9001:9001"

  cortex:
    container_name: cortex
    mem_limit: 1000m
    build: 
      dockerfile: ./vol/cortex/Dockerfile
      args:
        - VAST_VERSION=${VAST_VERSION:-latest}
        - CORTEX_VERSION=${CORTEX_VERSION:-latest}
    depends_on:
      - elasticsearch
    ports:
      - "9002:9001"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './vol/cortex/application.conf:/etc/cortex/application.conf'
      - './vol/cortex/jobs:/opt/cortex/jobs'
      - './analyzers:/opt/cortex/analyzers'

  vast:
    container_name: vast
    image: tenzir/vast:${VAST_VERSION:-latest}
    environment:
      - VAST_ENDPOINT=vast:42000
    ports:
      - ${VAST_PORT:-42000}:42000
    command:
      - start
    volumes:
      - vast-data:/var/lib/vast/

volumes:
  vast-data:
  elasticsearch-data:
  elasticsearch-logs:
  cassandra-data:
  thehive-data:
  thehive-index:
