---
openapi: 3.0.0
info:
  title: VAST Rest API
  version: "\"0.1\""
  description: "\nThis API can be used to interact with a VAST Node in a RESTful manner.\n\nAll API requests must be authenticated with a valid token, which must be\nsupplied in the `X-VAST-Token` request header. The token can be generated\non the command-line using the `vast rest generate-token` command."
servers:
  - url: https://vast.example.com/api/v0
security:
  - VastToken:
      []
components:
  securitySchemes:
    VastToken:
      type: apiKey
      in: header
      name: X-VAST-Token
paths:
  /query/new:
    post:
      summary: Create new query
      description: Create a new export query in VAST
      parameters:
        - in: query
          name: query
          schema:
            type: string
          example: :ip in 10.42.0.0/16 | head 100
          required: true
          description: "The query used, optionally including an open pipeline.\n"
        - in: query
          name: ttl
          schema:
            type: string
          example: 5.0m
          required: false
          description: "The time after which a query is cancelled. Use the /query/:id/next\nendpoint to refresh the TTL. To refresh the TTL without requesting\nfurther events, request zero events.\n"
        - in: query
          name: expand
          schema:
            type: boolean
          example: false
          required: false
          description: "Whether to use the expanded output schema.\n"
        - in: query
          name: flatten
          schema:
            type: boolean
            default: false
          required: false
          description: Flatten nested elements in the response data.
          example: false
        - in: query
          name: omit-nulls
          schema:
            type: boolean
            default: false
          required: false
          description: Omit null elements in the response data.
          example: false
        - in: query
          name: numeric-durations
          schema:
            type: boolean
            default: false
          required: false
          description: Render durations as numeric values.
          example: false
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                type: object
                example:
                  id: c91019bf-21fe-4999-8323-4d28aeb111ab
                properties:
                  id:
                    type: string
        401:
          description: Not authenticated.
        422:
          description: Invalid expression or invalid lifetime.
  /query/{id}/next:
    get:
      summary: Get additional query results
      description: Return `n` additional results from the specified query.
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          example: e84308a2-1ba4-4559-9e0f-597dfea4fd3e
          description: The query ID.
        - in: query
          name: n
          schema:
            type: integer
          required: false
          example: 10
          description: Maximum number of returned events
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      type: object
                    description: "The returned events, including a schema-ref that uniquely\nidentifies the schema for each row.\n"
                  schemas:
                    type: array
                    items:
                      type: object
                    description: "The schemas referenced in the events section of the same\nreply, using the same format as the `vast show schemas`\ncommand.\n"
                example:
                  events:
                    - schema-ref: foobarbaz
                      data:
                        ts: 2009-11-18T22:11:04.011822
                        uid: iKxhjl8i1n3
                        id:
                          orig_h: 192.168.1.103
                    - schema-ref: foobarbaz
                      data:
                        ts: 2009-11-18T22:11:04.011822
                        uid: iKxhjl8i1n3
                        id:
                          orig_h: 192.168.1.103
                  schemas:
                    - schema-ref: foobarbaz
                      definition: <type-definition>
        401:
          description: Not authenticated.
        422:
          description: Invalid arguments.
  /status:
    get:
      summary: Return current status
      description: Returns the current status of the whole node.
      parameters:
        - in: query
          name: component
          schema:
            type: string
          required: false
          description: If specified, return the status for that component only.
          example: index
        - in: query
          name: verbosity
          schema:
            type: string
            enum:
              - info
              - detailed
              - debug
            default: info
          required: false
          description: The verbosity level of the status response.
          example: detailed
      responses:
        200:
          description: OK.
          content:
            application/json:
              schema:
                type: object
              example:
                catalog:
                  num-partitions: 7092
                  memory-usage: 52781901584
                version:
                  VAST: v2.3.0-rc3-32-g8529a6c43f
        401:
          description: Not authenticated.
