version: '3'
services:
  matcher_client:
    image: tenzir/vastcloud:matcher
    build:
      context: ../../resources
      dockerfile: ../docker/matcher/matcher_client.Dockerfile
      args:
        - VAST_IMAGE
        - VAST_VERSION
