name: "Style Check"
on: pull_request
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  style:
    name: Style Check
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Clang Format
        run: |
          pip install --upgrade clang-format
          which clang-format
          clang-format --version
          git diff -U0 --no-color $(git merge-base origin/master HEAD) -- \
              '*.cpp' '*.cpp.in' '*.hpp' '*.hpp.in' |
            scripts/clang-format-diff.py -p1

      - name: CMake Format
        run: |
          pip install --upgrade cmake_format
          git diff --name-only --no-color --diff-filter=ACM $(git merge-base origin/master HEAD) -- "**CMakeLists.txt" "**.cmake" |
            xargs cmake-format --in-place
          git diff --exit-code

      - name: Black
        run: |
          pip install --upgrade black
          # Note: black fails when it doesn't have to do anything.
          git diff --name-only --no-color --diff-filter=ACM $(git merge-base origin/master HEAD) |
            grep '\.py$' |
            xargs --no-run-if-empty black || true
          git diff --exit-code

      - name: yamllint
        run: |
          pip install --upgrade yamllint
          git ls-files '*.yaml' '.yml' | xargs yamllint

      - name: Ansible Lint
        run: |
          pip install --upgrade ansible-lint
          ansible-lint --strict --profile production ansible

      - name: Terraform fmt
        run: |
          terraform fmt -check -recursive -diff

      - name: Markdown Lint
        run: |
          npm install --no-save markdownlint-cli
          npx markdownlint --ignore libvast/aux --ignore node_modules .
